### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by vhf** [thefrontside/ember-cli-twitter-typeahead#2]
Thanks for this addon.

I'm trying to use it on one of my projects, but I am getting an error on [this line](https://github.com/thefrontside/ember-cli-twitter-typeahead/blob/27d528535d3bd34eac8353d3dbc8e342a0a9d9c8/app-addon/components/twitter-typeahead.js#L64) : undefined is not a function.

Since this _validateEmail function is not defined in this addon, where does it come from? Am I missing a dependency?

Thanks a lot

**Comment by cowboyd** [comment]
Hi, @vhf thanks for reporting this issue. This was extracted from a specific project and this is a dependency that managed to leak in. I've fixed this on master, and will release an update soon.

**Comment by vhf** [comment]
Thanks for the fix!

**Comment by vhf** [comment]
Do you have an ETA for the release 0.0.6 fixing this issue?

**Comment by cowboyd** [comment]
@vhf oops, published.
