### ISSUE TITLE
Optional example /dummy app in the tests folder?

### ISSUE THREAD

**Issue by toranb** [thefrontside/ember-cli-twitter-typeahead#5]
First up - thank you for such a great OSS project! This looks great and will save me a TON of time otherwise spent reinventing the wheel :)

I see a lot of modern ember-cli addons use the built in dummy app (under tests) to show an example of the addon. This also helps from a testing standpoint because you can integration test the addon using that app (full stack). Would you be up to add something like this (if I submit a PR lets say).

Do you currently have a living "example app" that you'd prefer I use to port this with or will this be all new dev work?

**Comment by treyhunner** [comment]
:+1: I am also interested in using this app and haven't figured out how to use it yet.  A working example would be wonderful.

**Comment by toranb** [comment]
Because I never heard back I actually wrote a simple auto complete /type ahead that is HTMLbars friendly (requires ember 1.11)

https://github.com/toranb/ember-cli-auto-complete

**Comment by treyhunner** [comment]
@toranb I hadn't seen yours yet. I'll give it a try. Thanks!

**Comment by cowboyd** [comment]
@toranb I'm sorry that we dropped the ball on this. I admit, we end up fighting with twitter typeahead on every project, and the effort to extract this component was difficult since it was heavily customized.

I'm not sure what the future is for this plugin, and we'll also give yours a try.

**Comment by toranb** [comment]
@cowboyd sorry to cross promote my addon in your very project :( but as I didn't see much activity I thought it was worth mentioning to help others who (like me) needed a simple type-ahead

**Comment by cowboyd** [comment]
No it's fine, there are about 10 different typeahead solutions out there, and not more than a few based on twitter typeahed,  and it can be difficult to make heads or tails out of them. I actually think I'd like to move us behind a single typeahed solution that can get some proper love.
